from __future__ import annotations

"""
Migration 006 — Add app_users table for invite-only access control.

This table is the authorization layer for Phase 3 auth (Supabase magic link).
Authentication is handled by Supabase; this table answers "is this user approved
to access the PTI terminal?"

Roles:
  viewer  — can use the terminal (default)
  admin   — can use the terminal + future admin UI

Access statuses:
  pending   — invited but not yet approved
  approved  — has access
  revoked   — access removed (blocked at callback)

The supabase_uid column links an approved row to a Supabase Auth user.
It is nullable because rows can be pre-seeded (via SQL) before the user
has ever signed in and created a Supabase identity.

Invite workflow (SQL, no admin UI needed for soft launch):

  -- Approve a new user
  INSERT INTO app_users (email, role, access_status, invited_at, approved_at)
  VALUES ('user@example.com', 'viewer', 'approved', now(), now());

  -- Revoke access
  UPDATE app_users
  SET access_status = 'revoked', revoked_at = now(), updated_at = now()
  WHERE email = 'user@example.com';
"""

import sqlalchemy as sa
from alembic import op

revision = "006"
down_revision = "005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "app_users",
        sa.Column("id", sa.Text, primary_key=True, comment="UUID — generated by application or Supabase"),
        sa.Column("email", sa.Text, nullable=False),
        sa.Column("full_name", sa.Text, nullable=True),
        sa.Column(
            "role",
            sa.Text,
            nullable=False,
            server_default="viewer",
            comment="viewer | admin",
        ),
        sa.Column(
            "access_status",
            sa.Text,
            nullable=False,
            server_default="pending",
            comment="pending | approved | revoked",
        ),
        sa.Column(
            "supabase_uid",
            sa.Text,
            nullable=True,
            comment="Supabase Auth user UUID — set on first successful login",
        ),
        sa.Column("invite_token", sa.Text, nullable=True),
        sa.Column("invited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )

    # Unique + lookup indexes
    op.create_index("uq_app_users_email", "app_users", ["email"], unique=True)
    op.create_index("uq_app_users_supabase_uid", "app_users", ["supabase_uid"], unique=True)
    op.create_index("idx_app_users_access_status", "app_users", ["access_status"])
    op.create_index("idx_app_users_role", "app_users", ["role"])


def downgrade() -> None:
    op.drop_index("idx_app_users_role", table_name="app_users")
    op.drop_index("idx_app_users_access_status", table_name="app_users")
    op.drop_index("uq_app_users_supabase_uid", table_name="app_users")
    op.drop_index("uq_app_users_email", table_name="app_users")
    op.drop_table("app_users")
